### ISSUE TITLE
Support SHACL logical constraints not & and

### ISSUE THREAD

**Issue by dpetran** [fluree/db#321]
https://www.w3.org/TR/shacl/#core-components-logical

Transactions that violate logical constraints should return an error.

**Comment by cap10morgan** [comment]
Splitting out support for `or` and `xone` into separate issues. Mostly because the implementation work for `not` & `and` ended up being quite a bit more than we'd thought it would be.

**Comment by cap10morgan** [comment]
Deprioritizing this for now, so here are my notes on what I've done / discovered so far:

- Basic `sh:not` support is on `main` but it only supports PropertyShapes, not NodeShapes. The spec calls for both, so we're non-compliant for now.
- `sh:and` isn't really useful from what I can tell w/o NodeShape support (for extending those shapes w/ additional properties) so a partial implementation w/ only PropertyShape support doesn't seem worthwhile here.
- Supporting NodeShapes embedded in other NodeShapes required a more substantial refactor of the SHACL code than seemed worth prioritizing at the time.
- The other SHACL logical constraints (`sh:or` and `sh:xone`) are also supposed to support NodeShapes, but they would be useful w/ PropertyShape support alone. So that could be an option for a first pass down the road.

**Comment by dpetran** [comment]
Fixed in https://github.com/fluree/db/pull/755
