### ISSUE TITLE
Support for /multi-query on HTTP API [db-level]

### ISSUE THREAD

**Issue by aaj3f** [fluree/db#331]
### Description

- There is a valuable need in having the ability to issue multiple queries in one API request, as opposed to as separate HTTP requests, to resolve multiple queries at once with guarantees that the queries are resolved against the same block/commit (e.g. same data state)

### Acceptance Criteria

- An end user can submit an HTTP request where the body includes multiple queries (e.g. as a map `{ "userCount": { /* query */ }, "userData": { /* query */ }`)
- Fluree accepts the multi-query and resolves each query individually, returning a map of the same keys but with each key mapped to the query result of the provided query

### Implementation Details

- Previous implementations of Fluree moved from a pattern of keeping this API capability separate (e.g. /query and /multi-query) to a pattern of parsing messages to /query to determine if they were single queries or multi-query maps

**Comment by cap10morgan** [comment]
@aaj3f Should this be moved or have a counterpart issue (if there's work to do in here to support this, which I imagine there is) in [the http-api-gateway repo](https://github.com/fluree/http-api-gateway)?

**Comment by aaj3f** [comment]
@cap10morgan ah, thank you for the clarification -- yes I can make sure the work is described both for [db](https://github.com/fluree/db) and [http-api-gateway](https://github.com/fluree/http-api-gateway)

**Comment by bplatz** [comment]
In v2 we only had one `query` interface that replaced previously separate `query` and `multi-query` interfaces.

By looking at the query while parsing, as we are already inspecting it in detail, you can know if it is multi-query or query. We did this by not reserving any keys, but it could make life easier if we did reserve `:select` - but even then one can look at the contents of the key to see if it is a valid query (in which case it must be a multi-query).

**Comment by aaj3f** [comment]
@bplatz updated to add acceptance criteria and to reflect this implementation question

**Comment by zonotope** [comment]
@bplatz you mentioned [here](https://github.com/fluree/db/pull/304#discussion_r1062878653) that we previously made the decision to deprecate basic queries. Should we remove that functionality for JSON-LD since it's already backwards incompatible? A lot of our test suite still uses basic queries, so we would have to translate those tests to FQL/Analytical.

I mention this in the context of this ticket because I think we can use our validation logic to tell pretty easily if a given chunk of data is (1) a valid query, (2) a map with all it's values being valid queries, or (3) something else (which is invalid and should be rejected). Basic queries complicates that a little bit, so if we want to get rid of them anyway, now is a good time to do it.

**Comment by bplatz** [comment]
@zonotope I'm supportive of that. There is just one frequently used "Basic" query use case I'd like to see support for but it can come later. Basic queries allowed you to easily find data based on Collection (now Class), nodes that contain a predicate, and crawling the graph for a single subject. It is this last case that I hate loosing. My suggested alternative for this is a query that simply looks like:

```
{:select {:ex/brian [:*]}}
```

No need for a where clause at all.
