### ISSUE TITLE
Support for /history on HTTP API [db-level]

### ISSUE THREAD

**Issue by aaj3f** [fluree/db#332]
### Description

- There is a valuable need in having the ability to discover the history of diffs (assertions/retractions) to a subject/entity over the history of the ledger.

### Acceptance Criteria

- An end user can submit to the endpoint a subject identifier (e.g. @id but possibly others) and have returned a result that includes the summary of each commit where the subject was modified by a transaction, specifically with the details of that subject's particular assertion/retraction diffs (e.g. at commit # 3, the subject had retractions on these predicate-object values and assertions on these predicate-object values
- The behavior should align to some degree with the previous /history API behavior, documented here: https://developers.flur.ee/docs/overview/query/history_query/#history-query-with-auth-information 

### Implementation Details

- There has been a suggestion by Brian that we could merge the functionality of /history and /commit (formerly "/block") into on API where the syntax allows for parsing and executing down two different paths
- The documentation referenced above also describes "showAuth" and "prettyPrint" keywords. For reference, "prettyPrint" returned the retractions/assertions as JSON instead of tuples. "showAuth" provided the "auth ID" (e.g. pubkey hash) of the identity who issued the transaction resolving to the assertions/retractions at that block. Unclear if "showAuth" could be implemented today. "prettyPrint" may be irrelevant as commits are not natively JSON-LD

**Comment by bplatz** [comment]
@aaj3f I'd propose we remove the prettyPrint option here as we should now always be returning JSON-LD. I'm not sure what that flag would do.

Also the specific return format would be helpful to specify. I think it should look like the "db" JSON-LD file, but of course filtered to only include the adds/retracts specific to the history query.

**Comment by bplatz** [comment]
@aaj3f The reason, or at least one of the reasons, `showAuth` option was a separate flag is because it requires additional queries per commit item in the response to get that information, effectively doubling the amount of time the query would take to respond - which we wouldn't want to do if someone didn't want/need that info.

I believe what we are more accurately trying to accomplish is if we want to show any of the commit metadata along with the actual data changes. I'd favor a flag/option that better reflected this, such as `commitDetails`. I think at minimum we should include the commit signer, the transaction signer, and the commit timestamp if this flag is set.

**Comment by dpetran** [comment]
Splitting the `commitDetails` implementation to another ticket: #342.

**Comment by dpetran** [comment]
This introduces a new syntax for the history range.

Instead of:

`{:history "..." :t 1}` ;; at t
`{:history "..." :t [1]}` ;; from t
`{:history "..." :t [1 3]}` ;; from 1 to 3

It is now:

`{:history "..." :t {:from 1}}`
`{:history "..." :t {:from 1:to 1}}`
`{:history "..." :t {:from 1:to 3}}`
