### ISSUE TITLE
:spot error on query

### ISSUE THREAD

**Issue by jakep36** [fluree/db#356]
I'm getting a `:cause "No matching clause: :spot"` error when running:

```
{:select {'?s ["*"]}
           :where [['?s '?p '?o]]}
```

**Comment by cap10morgan** [comment]
I wonder if this error also occurs with these query variants:

`{:select '{?s [:*]}
   :where '[[?s ?p ?o]]}`

**Comment by mpoffald** [comment]
Probably yes. This error is being thrown because this is falling into the simple-subject-crawl process, which is being asked to use the `:spot` index but it [doesn't have a case for that](https://github.com/fluree/db/blob/main/src/fluree/db/query/subject_crawl/subject.cljc#L29).

**Comment by mpoffald** [comment]
This particular error was caused by this query being processed by simple-subject-crawl, which it shouldn't.

The fix for that was simple, but once I applied it, I found that our main query pipeline mishandles this query. I've created a separate bug for that: #384 

I'd like to keep this open and fix both at once, rather than apply the SSC fix and still have the query remain broken.
