### ISSUE TITLE
Allow user to force vector query result values for select graph crawls using context

### ISSUE THREAD

**Issue by bplatz** [fluree/db#390]
When performing a graph crawl in the `:select` clause of a query, if only a single value exists for a given property we always pull the value out of its vector format and return it.

A user will sometimes want to force the result to always be a vector... and we can express this fairly easily with the @context.

This is an example provided by @jdorety 

```
{
	"@context":{
		"f:allow": {
			"@container": "@set"
		}
	},
	"where": [["?policy", "rdf:type", "f:Policy"]],
	"select": { "?policy": ["*", { "f:allow": ["*"] }] },
}
```

Where it is expressing the values for "f:allow" should always be a vector, even if just a single value exists.

In doing this, the user doesn't have to check each value for the presence of the vector in their own code.

The other @container type that designates vectors/arrays, is @list - so we should allow the user to utilize that as well to get the identical result as above, as is in this example:

```
{
	"@context":{
		"f:allow": {
			"@container": "@list"
		}
	},
	"where": [["?policy", "rdf:type", "f:Policy"]],
	"select": { "?policy": ["*", { "f:allow": ["*"] }] },
}
```

**Comment by dpetran** [comment]
In the json-ld processor api standard there's a set of standardized options you can supply to the expand, compact, etc. functions. It includes [compactArrays](https://www.w3.org/TR/json-ld-api/#dom-jsonldoptions-compactarrays), which if set to `false` will never collapse arrays with a single entry into a "single cardinality" value.

On one hand, I don't think we currently have an api that allows specifying query opts, so that is something we'd have to add. On the other hand, people who are used to working with json-ld may expect that functionality.
