### ISSUE TITLE
Select '*' query without graph crawl

### ISSUE THREAD

**Issue by bplatz** [fluree/db#510]
We currently support this syntax: `{"select": {"?s": ["*"]} ...}` where you can retrieve all properties on a given subject returned from the `where` clause.

SPARQL also has a `SELECT *`, but it returns all variables bound in the where clause. We should support the same in FlureeQL as a prerequisite to support the corresponding SPARQL query.

```
{:select "*" ;; (or alternatively we currently support :* in CLJ)
 :where [[?s :ex/name "Joe"]
         [?s :ex/email ?email]
         [?s :ex/mobile ?mobile]]}
```

Is therefore the identical query to:
```
{:select [?s ?email ?mobile]
 :where [[?s :ex/name "Joe"]
         [?s :ex/email ?email]
         [?s :ex/mobile ?mobile]]}
```

**Comment by zonotope** [comment]
This might be a little tricky because the query infrastructure does not maintain the order that vars were bound in the where clause; vars are added to a generic hash map as they are bound. 

One way to do this could be to add metadata to the var binding to keep track of the order. We could also re-scan the where clause during the "select" formatting phase to get the var binding order on for the "*" case.

**Comment by bplatz** [comment]
For reference, SPARQL query parsing for the same query type is: db #511

**Comment by bplatz** [comment]
> We could also re-scan the where clause during the "select" formatting phase to get the var binding order on for the "*" case.

Because I'm guessing this isn't an overly common query select statement, I'd rather push all extra work into satisfying it only when used. I believe your re-parsing suggesting above likely accomplishes that, but certainly not positive this is the case or there aren't better ways.
